### ISSUE TITLE
request: default wordlist and document password cracking

### ISSUE THREAD

**Issue by JarbasAl** [JonStratton/skill-aircrack#1]
really nice so it would just work out of the box

use skill settings for setting wordlist path optionally

**Comment by JonStratton** [comment]
Good idea making that a skill setting. And maybe making the interface selection a skill setting too. 

Not sure how the audio would flow as far as defaulting / choosing a wordlist yet. Didnt like hardcoding to rockyou. Maybe ill just make it wget a common password.1st file, and allow the user overwrite with something like. "Use Wordlist dot txt" and to a locate / skill setting on that.

**Comment by JonStratton** [comment]
Defaulted the wordlist by pulling in a smaller one from https://github.com/danielmiessler/SecLists. Also made it a setting, so if someone wants to change it they dont have to touch the main code. Changed under 0b66270fdfc0181135770a88af8ead5b59b1f070.
