### ISSUE TITLE
'skill' in skill title

### ISSUE THREAD

**Issue by krisgesling** [JonStratton/skill-aircrack#8]
Hi Jon,

This is not an "issue" so much as a little housekeeping we are doing for the [Marketplace](https://market.mycroft.ai/). We are asking Skill Developers to consider removing the word "skill" from the title of all skills in your readme. 

The intention is to provide a more consistent experience as users explore the Skills available, and when Skills are verbally suggested through the device itself. 

If you are happy to do so, it would be great if you could just delete the word 'skill' from the main title of the readme. No need to update anything else. If you then resubmit the Skill using `mycroft-msk upgrade` we will be able to merge it quickly as there are no code or functionality changes.

Thanks
Gez

**Comment by JonStratton** [comment]
@krisgesling , thanks; Ive made the requested change into the main branch. As I have #809 on this skill out there already, I will either add this change to that PR or create a new one once that one moves along.

**Comment by krisgesling** [comment]
Thanks Jon, sorry for the delay in skill reviews too. With 19.02 out of the way we'll be clearing that backlog now. However to make it easier to get your skill straight into the 19.02 repo, it would be best to close #809 and resubmit with new changes using `mycroft-msk submit /path/to/skill`
